/*
 *      File C_7BITBL.C
 *      A Table to Convert the Index of the KS Fixed Hangul Code
 *      to the 7 Bit Fixed Hangul Code
 *      '95.4.28
 *      Written by Inkeon Lim
 */


#include "hancode.h"


const byte _cnvtbl_7BITHAN[2350 * 2] = {
    "_U_V_W_X_Y_Y_Y_Z_[_\\_]_^___`_`_a_b_b_c_d_e_f_g_h_h_h_i_i_i_i_j_j_j_j_j"
    "_j_k_l_m_n_o_o_p_q_r_r_s_s_t_t_t_u_v_w_w_w_x_y_y_z_{_|_}_}_~`!`#`#`$`%"
    "`&`'`'`'`'`'`(`)`*`+`,`-`-`-`.`/`0`1`1`2`3`4`5`5`5`5`5`6`7`8`8`8`8`9`:"
    "`:`;`;`;`;`;`<`=`=`=`=`=`>`?`@`A`B`C`D`D`E`F`G`H`H`H`H`I`J`J`J`K`K`L`L"
    "`L`L`L`L`M`N`O`P`Q`R`S`S`T`U`V`W`X`Y`Y`Z`Z`[`[`\\`\\`]`]`^`^`^`_```a`b`c"
    "`d`d`e`f`f`f`g`h`i`i`i`j`j`j`j`j`j`j`j`j`k`l`m`m`m`n`o`o`o`p`q`q`q`q`q"
    "`q`r`r`r`s`s`s`s`t`u`v`v`w`x`y`y`z`{`|`}`~`~`~`~a@a@aAaBaBaBaBaBaBaCaD"
    "aEaFaGaHaIaIaIaIaIaJaJaJaJaKaKaKaKaKaKaKaLaLaLaLaLaLaMaMaNaOaPaPaPaQaQ"
    "aRaRaSaTaTaUaVaWaWaWaWaXaYaZa[a[a\\a]a]a^a_b@bAbBbCbDbEbFbGbGbHbIbJbKbL"
    "bMbNbObObObObObPbQbRbSbTbUbUbVbWbWbWbWbXbYbZb[b\\b]b]b]b^b^b^b_c@cAcAcB"
    "cBcCcDcEcEcEcFcGcHcIcIcJcKcLcMcNcOcOcOcOcPcQcQcQcQcQcQcRcRcRcRcRcRcScT"
    "cTcUcUcVcVcVcVcVcWcWcWcXcXcXcXcXcYcYcYcZcZcZc[c\\c]c^c_c_d@d@d@dAdBdCdD"
    "dDdDdEdFdGdHdHdIdJdJdKdKdLdMdNdOdPdQdRdSdSdTdUdVdWdWdXdXdYdZd[d\\d]d^d_"
    "d_e@e@eAeAeBeCeCeDeDeEeEeEeFeGeHeIeJeKeLeLeMeNeNeNeOeOePePePePePePePeP"
    "eQeReSeTeUeUeUeVeWeWeXeXeXeXeXeXeYeZe[e\\e]e^e_e_e_f@fAfBfCfDfEfEfFfGfH"
    "fHfHfIfIfIfIfJfJfKfKfKfKfKfLfMfNfOfPfPfQfRfSfTfTfUfVfWfXfYfZf[f\\f\\f]f^"
    "f_g@gAgBgCgCgCgCgDgDgEgEgFgFgGgGgGgGgHgIgJgKgLgLgMgMgMgMgNgNgOgPgPgPgQ"
    "gQgQgQgQgQgQgQgRgSgSgSgTgTgTgTgUgUgVgWgWgWgXgXgYgYgZg[g[g\\g\\g\\g]g^g_h@"
    "hAhBhBhChDhDhDhDhDhEhFhFhFhFhFhFhGhHhIhJhKhLhMhNhOhOhOhPhQhRhShThUhVhW"
    "hXhYhZh[h[h[h\\h]h^h_i@iAiBiCiDiEiFiGiHiIiJiKiKiLiLiMiNiOiPiQiRiSiTiUiV"
    "iViViViWiXiYiZi[i\\i]i^i^i^i^i^i_i_i_i_i_i_i_j@j@j@j@j@jAjBjCjDjEjFjGjH"
    "jHjIjIjIjIjIjIjIjIjIjIjJjKjLjMjNjNjNjOjPjQjRjSjTjUjVjWjWjWjXjYjZj[j\\j]"
    "j^j_k@kAkBkCkDkEkFkGkGkHkIkJkKkLkMkNkOkPkQkRkSkTkTkTkUkVkVkVkVkVkWkXkY"
    "kZkZk[k[k\\k]k]k]k^k_l@lAlBlBlClClClDlDlElFlFlFlGlHlHlIlJlKlLlMlMlNlOlP"
    "lQlQlQlQlQlQlQlQlQlQlQlRlRlRlRlRlSlTlUlVlWlXlXlXlYlYlZl[l[l\\l]l^l_l_m@"
    "m@m@m@m@mAmAmAmBmBmCmCmDmEmEmFmGmHmImJmJmKmLmLmLmMmNmOmPmQmRmRmSmTmUmV"
    "mVmWmXmYmZm[m\\m]m^m_n@nAnAnBnBnCnDnDnDnDnDnEnFnGnGnHnHnInJnKnLnMnNnNnO"
    "nOnPnPnPnPnPnQnRnSnTnUnVnWnWnXnYnYnYnZn[n[n\\n]n^n_o@oAoBoBoCoCoCoDoDoD"
    "oEoEoEoEoEoFoGoHoHoIoJoJoKoKoLoMoNoNoNoNoNoNoOoOoOoOoOoPoPoPoPoPoPoQoQ"
    "oRoSoSoSoSoToUoVoWoWoXoXoYoZo[o\\o]o^o_p@p@p@p@p@p@pApApBpCpDpEpFpFpGpG"
    "pGpGpGpHpIpIpJpKpLpLpLpLpMpNpNpOpOpOpOpOpOpOpPpPpPpPpPpQpRpRpRpRpSpTpU"
    "pVpWpWpWpWpWpXpYpZp[p[p\\p\\p\\p\\p\\p\\p\\p\\p]p^p^p_p_q@q@qAqBqCqDqEqFqGqHqI"
    "qJqKqLqLqLqLqMqNqNqNqOqOqOqPqQqQqQqQqQqQqRqSqTqTqUqUqVqVqVqWqXqYqZq[q["
    "q\\q]q^q_r@rArBrBrBrCrCrDrDrDrDrDrErErErErErErFrGrGrHrIrIrJrJrKrLrMrMrM"
    "rMrMrMrNrNrNrNrNrNrOrOrOrOrOrOrPrPrQrQrQrQrQrQrRrSrTrUrVrWrWrXrYrYrYrZ"
    "r[r[r\\r\\r\\r]r]r]r^r^r_s@s@sAsAsAsBsBsBsCsDsDsEsFsGsHsIsJsKsLsMsNsOsPsQ"
    "sRsSsTsUsVsWsXsYsZsZs[s\\s\\s\\s\\s]s^s_s_s_s_s_s_s_s_s_t@tAtBtCtCtCtCtDtE"
    "tFtFtFtFtGtGtGtHtItItItItItJtJtJtJtJtJtJtJtJtJtJtJtKtLtLtLtLtLtLtLtLtL"
    "tLtLtLtMtNtOtPtPtPtQtRtStStStStTtUtVtWtWtXtYtZt[t\\t]t^t_u@u@u@uAuBuCuD"
    "uEuFuFuGuHuIuJuKuLuLuLuLuMuNuOuPuQuRuSuSuSuTuUuVuWuWuWuWuXuYuZu[u\\u]u^"
    "u^u_v@vAvBvCvDvDvEvFvGvHvIvJvKvKvLvMvNvOvPvQvRvRvRvSvTvTvUvVvWvWvXvYvZ"
    "vZvZvZvZv[v[v\\v]v^v_w@wAwAwBwCwDwEwFwFwGwHwIwJwJwJwJwKwLwMwMwMwMwMwMwN"
    "wNwOwOwOwOwOwOwPwQwRwRwRwRwRwSwTwUwVwWwWwWwXwYwZw[w\\w]w^w_w_w_x@x@xAxA"
    "xBxCxCxCxCxDxDxExFxFxFxGxHxIxJxKxLxLxLxLxMxMxNxOxPxQxQxRxSxSxTxTxTxTxT"
    "xTxTxUxUxUxUxUxVxWxXxYxZxZx[x\\x]x^x_y@yAyByCyDyEyFyFyGyGyHyIyJyJyKyLyM"
    "yMyMyNyNyNyOyOyPyQyQyQyQyQyQyQyQyQyQyRySyTyUyVyWyXyYyZy[y\\y]y^y_y_y_z@"
    "z@zAzBzBzBzBzCzCzCzDzEzFzGzGzHzIzIzJzJzKzLzMzMzMzMzMzMzMzMzMzNzNzNzNzN"
    "zNzNzOzOzPzPzQzRzSzTzTzTzUzVzWzXzYzYzYzZzZzZzZzZzZzZz[z[z[z[z\\z]z^z_{!"
    "{#{#{${%{&{'{'{({){*{+{,{-{.{/{0{1{2{3{3{4{5{5{5{5{5{6{7{7{7{7{7{7{7{8"
    "{9{9{9{9{:{;{<{={={={={={>{>{>{>{>{?{@{@{@{@{@{@{@{A{A{A{A{A{A{A{A{A{A"
    "{A{A{A{B{C{C{D{D{D{D{D{D{D{D{D{E{F{F{F{G{H{I{J{J{J{J{K{L{M{N{O{P{Q{R{S"
    "{T{U{V{W{X{Y{Z{Z{[{[{[{[{\\{]{]{]{]{]{]{^{_{`{a{b{c{d{d{e{f{g{g{h{h{h{h"
    "{h{i{i{j{j{j{j{k{l{m{n{n{n{o{p{p{p{q{q{r{r{r{r{r{r{r{r{r{s{t{u{v{w{x{x"
    "{y{z{z{{{{{|{|{|{|{|{|{|{}{}{}{}{}{~|!|!|!|#|#|#|$|%|&|'|'|(|(|)|*|+|,"
    "|-|.|/|0|1|1|1|2|3|3|4|5|6|7|7|7|7|7|7|7|8|9|:|:|;|<|=|>|?|?|@|@|A|B|B"
    "|B|C|C|D|E|F|F|F|F|G|G|G|H|I|J|K|L|L|M|N|N|N|N|N|N|N|O|O|O|O|P|P|Q|Q|R"
    "|R|R|R|S|S|S|S|S|S|S|T|T|U|U|U|U|U|U|V|V|V|V|W|W|X|Y|Z|Z|Z|[|\\|]|^|_|_"
    "|`|a|b|c|d|e|e|f|g|h|h|i|j|k|l|m|n|n|n|n|o|o|o|p|q|r|s|s|t|u|u|u|v|w|x"
    "|y|z|{|{|{|{|{|{|{|{|{|||}|~}!}#}$}$}%}%}%}%}%}&}&}&}&}&}'}(}(})})})})"
    "}*}*}*}*}+}+}+}+}+}+}+},},},},},}-}.}/}/}0}0}1}1}2}3}3}3}3}3}4}5}6}7}8"
    "}9}9}:};}<}=}>}?}?}@}A}B}C}D}E}F}G}H}H}H}H}H}H}I}I}I}J}K}L}M}N}N}N}O}O"
    "}P}P}Q}R}R}R}R}R}S}T}U}U}U}U}V}W}W}W}W}X}Y}Z}[}\\}\\}\\}]}]}]}]}]}^}^}^}^"
    "}^}_}`}a}a}b}b}c}c}d}e}e}e}e}e}e}e}e}f}f}f}f}f}f}g}h}i}j}j}j}k}l}m}n}o"
    "}p}q}r}s}t}u}v}v}w}x}y}z}{}|}}}}}~}~~!~#~$~$~%~&~&~'~(~(~)~)~*~+~,~-~."
    "~/~/~/~/~/~0~1~2~3~4~5~5~6~7~8~8~8~8~9~:~;~<~<~=~>~?~@~@~A~B~C~D~E~F~F"
    "~F~F~F~F~G~H~H~H~H~H~I~J~J~J~J~J~K~L~M~N~N~O~P~P~P~Q~R~R~R~S~S~S~S~S~T"
    "~T~T~U~V~V~V~V~W~W~W~W~W~W~X~Y~Z~[~[~[~\\~]~^~_~_~`~a~b~c~c~c~c~c~d~d~e"
    "~f~g~g~h~~"
};
